import { Navbar } from "@/components/navigation/navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter, Syne } from "next/font/google";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter", display: "swap" });
const syne = Syne({ subsets: ["latin"], variable: "--font-syne", display: "swap" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${syne.variable} bg-background text-foreground`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
